name: redfin_prediction_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - statsmodels
  - pmdarima
  - scikit-learn
  - pytest
  - pytest-mock
  - streamlit
  - requests
  - pip
  - pip:
      - black
      - flake8
      - mypy
      - toml==0.10.2
