name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: 'latest'
        auto-update-conda: true
        activate-environment: false

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Set Conda solver to classic
      run: |
        conda config --set solver classic  # Explicitly set the classic solver backend

    - name: Create and activate conda environment
      run: |
        conda env 
